### ISSUE TITLE
[FLUFFOS] Syntactic sugar for evaluate() reporting diagnostic that can't be configured

### ISSUE THREAD

**Issue by gesslar** [jlchmura/lpc-language-server#10]
Function values can be invoked by using evaluate (). But there is another way to invoke them using this syntactic sugar:
```c
varargs string make_bigger_string(mixed args...) {
    string result = "";
    int sz = sizeof(args);

    while (sz--) {
        result = args[sz] + result ;
    }

    return result;
}

void main() {
    function the_function_I_want_to_call_is = (: make_bigger_string :);
    string result ;

    result = (*the_function_I_want_to_call_is)("hello", " ", "world");

    printf("result = %s\n", result) ;
}
```
And it definitely is offended by this syntax.
![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/aef22694-ad94-4ce5-87aa-535c4ea90e1d)

or... maybe less offended than it doesn't really know what to do with it? idk. but it's littering my problems with warnings.

**Comment by gesslar** [comment]
I forgot to add what it's actually saying, which is this. It's the same thing for all of these.
![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/c15a2f5b-4685-47ec-8c09-c811d652455e)

**Comment by jlchmura** [comment]
> it doesn't really know what to do with it?
That's exactly right.. its warning you that it doesn't know what function this is references and therefore can't validate if you're passing the correct parameters. 

You should be able to turn this off via lpc-config, so I'll fix that.  You can also convince me that "warning" level for this diagnostic is too aggressive.  Maybe the default level should be "none" and you can opt in to it being a higher, reportable level?

**Comment by jlchmura** [comment]
In version 1.0.15, this will now be reported as diagnostic code `functionUnknown` with a default level of `hint`.
