### ISSUE TITLE
Unable to open when going to definition

### ISSUE THREAD

**Issue by serenez** [jlchmura/lpc-language-server#118]
! [image] (https://github.com/user-attachments/assets/ab2b8b3f-9cca-4f25-b9a3-c899ae46e48c)
When I try to use the go-to-definition function on a function, an unexpected error occurred and the editor cannot be opened.

**Comment by serenez** [comment]
![image](https://github.com/user-attachments/assets/1ba23640-7ed3-4dd6-a692-a456130c3713)

**Comment by serenez** [comment]
![image](https://github.com/user-attachments/assets/e212b703-5418-472c-bb94-1428e00d305c)

**Comment by jlchmura** [comment]
Can you post your server log?

**Comment by serenez** [comment]
`Starting LPC Language Server
Info 0    [00:19:43.701] Starting TS Server

Info 1    [00:19:43.702] Platform: win32 NodeVersion: v20.18.1 CaseSensitive: false

Info 2    [00:19:43.702] ServerMode: 0

Info 3    [00:19:43.729] getConfigFileNameForFile:: File: e:/24xinduobao/inherit/char/npc.c ProjectRootPath: undefined:: Result: e:/24xinduobao/lpc-config.json

Info 4    [00:19:43.729] Creating configuration project e:/24xinduobao/lpc-config.json

Info 5    [00:19:44.104] Config: e:/24xinduobao/lpc-config.json : {
 "rootNames": 4062,
 "options": {
  "configFilePath": "e:/24xinduobao/lpc-config.json",
  "rootDir": "e:/24xinduobao/",
  "rootDirs": [
   "e:/24xinduobao/"
  ],
  "driverType": 1,
  "globalIncludeFiles": [
   "/include/globals.h"
  ],
  "libIncludeDirs": [
   "e:/24xinduobao/include",
   "e:/24xinduobao/mudcore/include"
  ],
  "diagnostics": false,
  "sefunFile": "e:/24xinduobao/adm/single/simul_efun.c",
  "masterFile": "e:/24xinduobao/adm/single/master.c",
  "playerFile": "e:/24xinduobao/clone/user/user.c",
  "configDefines": {}
 }
}

Info 6    [00:19:45.062] Starting updateGraphWorker: Project: e:/24xinduobao/lpc-config.json

Info 7    [00:19:51.262] Finishing updateGraphWorker: Project: e:/24xinduobao/lpc-config.json projectStateVersion: 1 projectProgramVersion: 0 structureChanged: true structureIsReused:: Not Elapsed: 6200.670700000001ms

Info 8    [00:19:51.262] Project 'e:/24xinduobao/lpc-config.json' (Configured)

Info 9    [00:19:51.263] 	Files (4063)


Info 10   [00:19:51.263] -----------------------------------------------

todo - markAutoImportProviderAsDirty
Info 11   [00:19:51.268] Project 'e:/24xinduobao/lpc-config.json' (Configured)

Info 11   [00:19:51.268] 	Files (4063)


Info 11   [00:19:51.268] -----------------------------------------------

Info 11   [00:19:51.268] Open files: 

Info 11   [00:19:51.268] 	FileName: e:/24xinduobao/inherit/char/npc.c ProjectRootPath: undefined

Info 11   [00:19:51.268] 		Projects: e:/24xinduobao/lpc-config.json

DirectoryWatcher:: Triggered with e:/24xinduobao/.git/objects/maintenance.lock :: WatchInfo: e:/24xinduobao 1 undefined Config: e:/24xinduobao/lpc-config.json WatchType: Wild card directory
Info 11   [00:19:51.272] Project: e:/24xinduobao/lpc-config.json Detected ignored path: e:/24xinduobao/.git/objects/maintenance.lock

Elapsed:: 0.20870000000013533ms DirectoryWatcher:: Triggered with e:/24xinduobao/.git/objects/maintenance.lock :: WatchInfo: e:/24xinduobao 1 undefined Config: e:/24xinduobao/lpc-config.json WatchType: Wild card directory
DirectoryWatcher:: Triggered with e:/24xinduobao/.git/objects/maintenance.lock :: WatchInfo: e:/24xinduobao 1 undefined Config: e:/24xinduobao/lpc-config.json WatchType: Wild card directory
Info 12   [00:19:51.272] Project: e:/24xinduobao/lpc-config.json Detected ignored path: e:/24xinduobao/.git/objects/maintenance.lock

Elapsed:: 0.028300000000854197ms DirectoryWatcher:: Triggered with e:/24xinduobao/.git/objects/maintenance.lock :: WatchInfo: e:/24xinduobao 1 undefined Config: e:/24xinduobao/lpc-config.json WatchType: Wild card directory
todo - getExtractStringType - is this needed?
todo - getExtractStringType - is this needed?
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
TODO - narrowTypeByTypePredicate is assumedTrue
todo - getExtractStringType - is this needed?
todo - getExtractStringType - is this needed?
TODO - narrowTypeByTypePredicate is assumedTrue
todo - getReturnTypeFromBody - possible FluffOS function shortcut
todo - getReturnTypeFromBody - possible FluffOS function shortcut
`
After clicking to go to the definition, there was no log output and an error window popped up directly

**Comment by jlchmura** [comment]
This will be fixed in release 1.1.13
