### ISSUE TITLE
[FLUFFOS] Find All References quirks

### ISSUE THREAD

**Issue by michaelprograms** [jlchmura/lpc-language-server#18]
I've been playing around with the `Find All References` feature and noticing some weird things happening.

![image](https://github.com/jlchmura/lpc-language-server/assets/1260602/9ec9743b-39ab-4114-96c4-08baa0a36b69)

1. ~~Maybe not an issue so much as a nitpick, but the matched function is shown in full, with visible line returns characters. This is alright for small functions but functionally useless for larger functions as it ends up truncating with `...` anyway. I would expect only the opening line of the function to match.~~ Moved to #20 

2. ~~Sometimes it matches fluffos efuns that should not be matched. I have not been able to reproduce this 100%, maybe it was fixed in a newer release than I originally pulled, but the code snippet this is matching is essentially this:~~ Moved to #23
```c
nomask varargs void quit_character () {
    character_exit();
    flush_messages();
}
``` 
 

3. Right clicking & Find All References on a function declaration, (ex: `nomask void character_exit ()`) results in "No results. Try running a previous search again:" most of the time, some functions seem to work but others don't work at all. Doing the same on a usage of `character_exit();` will bring up valid results sometimes, but it will still fail and say "No results. Try running a previous search again:". It seems to work better if the references are in the same file.

**Comment by jlchmura** [comment]
Part of this ticket was split into #20
