### ISSUE TITLE
[FLUFFOS] There can be multiple includes on a single line

### ISSUE THREAD

**Issue by jlchmura** [jlchmura/lpc-language-server#27]
The following code will compile in FluffOS, and should be handled by the preprocessor:
```
#include <test.h>#include<test2.h>
```

**Comment by michaelprograms** [comment]
I think this relates to the `#include <std.h>%^RESET%^` weirdness we were discussing the other day. It seems anything trailing the first closing `>` or `"` is ignored in Fluffos, so in this case `test2.h` is not even included. It should probably give a similar error to the `#include <std.h>%^RESET%^` scenario: `extraneous input '#'`.

I created a simple example:
```c
// a.h
#define A "A"
```
```c
// b.h
#define B "B"
```
```c
// test.c
#include "a.h"#include "b.h"

void test() {
    write(A+" "+B+"\n");
}
```

```
>  update /test.c
Updating /test.c...
/test.c line 4: Error: Undefined variable 'B'
  writ"A"+" "+B+"\n")
                    ^

*Error in loading object '/test'
```

**Comment by jlchmura** [comment]
I'm closing this as fixed in v2.  Even though fluff will ignore all tokens after the the first include directive, I made the decision the language server should be more proactive about alerting the user because this is a possible mistake.  Therefore, v2's parser will report an "Expected newline after directive." problem in this situation.
