### ISSUE TITLE
[FLUFFOS] Language server does not like !!

### ISSUE THREAD

**Issue by gesslar** [jlchmura/lpc-language-server#31]
![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/ea950aea-c3f9-4996-9de4-ca7b0c1d1121)

**Comment by jlchmura** [comment]
Fixed in commit https://github.com/jlchmura/lpc-language-server/commit/9181004fce63d6e5a1280b559e4c964ca87aadfe

Will be included in v21.
