### ISSUE TITLE
Plugin Loading is Slow

### ISSUE THREAD

**Issue by serenez** [jlchmura/lpc-language-server#37]
After updating to versions 1.0.22 and 1.0.23, the plugin takes a long time to load every time I open a file. However, I did not have this issue with version 1.0.21 and earlier.

![image](https://github.com/jlchmura/lpc-language-server/assets/38424953/a638a5fb-4ecc-41c9-85a6-24b7f4d37ca8)

**Comment by serenez** [comment]
Issue with Plugin Loading and Function Declaration in FluffOS。
I've noticed a couple of issues since updating to the latest versions of the plugin. Firstly, the plugin loading time has become significantly slower compared to the previous versions. Specifically, after updating to versions 1.0.22 and 1.0.23, the plugin takes a considerable amount of time to load upon opening a file, which was not the case with version 1.0.21 and earlier.

Secondly, I've encountered a problem with the keys() function under the FluffOS driver. It appears that the function is not declared, which is causing some issues with the code.

Additionally, there seems to be an issue with object inheritance when not using the new declaration for an object. For instance, when I create a new command a.c with the following content:

int main(object me, string arg);
The me->set() and other user object functions do not seem to be inheritable or referenceable properly. Could this be optimized? It would be great if these functions could be properly inherited and referenced without having to explicitly declare them with new.

I believe addressing these issues would greatly improve the user experience and the functionality of the plugin. Any assistance or insights on this matter would be appreciated.

Thank you for your attention to these concerns.

**Comment by serenez** [comment]
![image](https://github.com/jlchmura/lpc-language-server/assets/38424953/37323bf6-ef72-44e2-8498-dce4c7593d4b)

**Comment by serenez** [comment]
![image](https://github.com/jlchmura/lpc-language-server/assets/38424953/822b5222-e57e-49e3-983a-89c9ef4ef597)
I will still report these two errors

**Comment by jlchmura** [comment]
Thank you for reporting.  I will look in to the startup speed issue.  You can also speed things up by excluding any folders that contain unneeded or junk lpc files (see [exclude](https://github.com/jlchmura/lpc-language-server#exclude-dirs---exclude))

Re: the `Unable to validate function` diagnostic error - code analysis is still a work in progress.  It is recommended that you disable semantic diagnostics until that feature is complete. You can disable them by [setting diagnostics to `off`](https://github.com/jlchmura/lpc-language-server#disabling-code-diagnostics) if your lpc config file:
```json
{
  "diagnostics": "off"
}
```

**Comment by jlchmura** [comment]
missing `keys()` efun was split into #38

**Comment by jlchmura** [comment]
> The me->set() and other user object functions do not seem to be inheritable or referenceable properly.

@serenez This feature is being worked on.  Also, since `me()` is not a standard FluffOS efun, I am assuming it is an sefun in your lib?  Have you set lpc-config to point to the proper sefun file?  Example:
```json
{
  "files": {
    "simul_efun": "/secure/simul_efun.c" // customize this location specific to your lib 
  }
}
```

**Comment by serenez** [comment]
> > The me->set() and other user object functions do not seem to be inheritable or referenceable properly.
> 
> @serenez This feature is being planned but not yet supported. The issue is that the language server does not know what type of object me is. One proposal is to use doc comments to give it a hint if it cannot be determined automatically by the type checker. Stay tuned!

Thank you for your efforts, which have enabled us to use such a convenient plugin. Thank you again!

**Comment by jlchmura** [comment]
I am closing this issue, as it was largely resolved in v25 & 26
