### ISSUE TITLE
Allow lpc-config to be located anywhere

### ISSUE THREAD

**Issue by jlchmura** [jlchmura/lpc-language-server#40]
Allow lpc-config file to be placed anywhere within the project with the proposed rule that:

1. If lpc-config does not contain a `rootDir` property, the location of the config file will be used as the lib root dir.
otherwise, 
2. The `rootDir` path will be used as the lib root dir.

**Comment by mpconley** [comment]
I'd like to have the option to have lpc-config.json be elsewhere than the root of the source for my game. I only have directories in the root currently. As you know, we'll find most settings like this in `.vscode` `.github` or similar. Perhaps a `.lpc` folder?

-Tamarindo

**Comment by jlchmura** [comment]
@mpconley This describes what I'm proposing: [mudlibDir setting](https://github.com/jlchmura/lpc-language-server/tree/mudlibDir#mudlib-root---mudlibdir).  That should allow the lpc-config.json file to be placed anywhere with the project, and the language server will simply use the first one it finds.

**Comment by mpconley** [comment]
@jlchmura like this, right?

<img width="848" alt="Screenshot 2024-11-09 at 3 09 14 PM" src="https://github.com/user-attachments/assets/bc8ecb73-0809-47b0-9632-a8d1b9561b75">

**Comment by mpconley** [comment]
Thanks, got it, and all is right with the world.
