### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by serenez** [jlchmura/lpc-language-server#43]
Could you please add an option to the Chinese document page so that we can use Chinese documents more conveniently? We have a mud circle, and most of us are Chinese, including myself, whose English is not very good. A lot of the floating prompts also need to be translated again or directly checked in Chinese Wikipedia. So, can this feature be added? If it's too troublesome, then it's okay not to do it. I don't understand the process of implementing this feature, so if it's difficult, there's no need to do it."
![image](https://github.com/user-attachments/assets/cc1cfb1f-aaf0-4f92-9b8f-4af97efa769f)
https://www.fluffos.info/zh-CN/

**Comment by jlchmura** [comment]
Thanks for the suggestion.  Once I add support for localization in general, I'll reach out for assistance adding Chinese-specific content.
