### ISSUE TITLE
#define statements are not syntax highlighted correctly

### ISSUE THREAD

**Issue by michaelprograms** [jlchmura/lpc-language-server#50]
![image](https://github.com/user-attachments/assets/e11012fc-2732-43fe-b1ec-ee304ea4b7c5)

`#define` statements are not coloring the `#` in syntax highlighting.

`#ifndef`, `#undef`, and `#endif` are all syntax highlighting correctly, it's only `#define` statements that are different.

Unsure if this is effecting LDmud as well or just FluffOS.

**Comment by jlchmura** [comment]
Impacts LD as well.
