### ISSUE TITLE
[FLUFFOS] Problem parsing @text

### ISSUE THREAD

**Issue by gesslar** [jlchmura/lpc-language-server#6]
Getting the following errors when the server encounters `@` text.

![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/b284a6e7-efe9-491f-890c-8fbd91773ccf)

![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/b2d0578b-a202-4e41-a086-2615064b9450)

```c
inherit STD_ITEM ;

void setup() {
    set("id", ({ "doorbell", "doorbell_obj", "cord", "rope", "bell cord", "bell", "buzzer" }) );
    set("long", @text

   This is a simple doorbell. You can ring it if you would like to alert
those living inside.

text
);
    set("prevent_get", 1);
    set("attached", 1);
}
```

my json
```json
{
    "type" : "fluffos",
    "master" : "/adm/obj/master.c",
    "simul_efun" : "/adm/obj/simul_efun.c",
    "include" : [ "/include" ],
    "exclude" : [ ".git" ],
    "diagnostics" : "off"
}
```

**Comment by jlchmura** [comment]
Thanks for posting your config!  The `driver` and `files` sections are incorrect in the config, and the former is causing it to run in LDMud mode, which is why it can't parse the text formatting block.  Try this config:
```json
{    
    "driver": {
        "type": "fluffos" 
    },
    "files": {
        "master" : "/adm/obj/master.c",
        "simul_efun" : "/adm/obj/simul_efun.c",
    },    
    "include" : [ "/include" ],
    "exclude" : [ ".git" ],
    "diagnostics" : "off"
}
```
