### ISSUE TITLE
Operator '+' cannot be applied to types 'bytes' and 'bytes'

### ISSUE THREAD

**Issue by michaelprograms** [jlchmura/lpc-language-server#83]
![image](https://github.com/user-attachments/assets/5ff6da3e-b5d2-4d17-8988-6e470ad69e68)
![image](https://github.com/user-attachments/assets/987c468c-5a37-47c4-8069-ca7a84782002)

`buffer + buffer` is valid LPC, this shouldn't be showing an error squiggly.
```c
> eval printf( "%O\n", allocate_buffer(1)+allocate_buffer(1) )
BUFFER ( /* sizeof() == 2 */
  0x0,
  0x0
)
Complete (0.57 ms)
```

**Comment by jlchmura** [comment]
Fixed in 1.1.5.
