### ISSUE TITLE
[FLUFFOS] Default parameters causing errors

### ISSUE THREAD

**Issue by gesslar** [jlchmura/lpc-language-server#9]
In FluffOS, you can specify default parameters by adding a colon and then function that evaluates as the result which will be the parameter value if it is not passed.

```c
void runit(int x: (: 10 :)) {
    printf("%d\n", x) ;
}
```

![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/6a13a585-63f1-49af-b75c-6a909887493a)
![image](https://github.com/jlchmura/lpc-language-server/assets/1266935/5ecbea6e-cbca-441d-ae70-3edfb9f92f02)

**Comment by jlchmura** [comment]
Forgot about those fancy default param functions!
